Update package.json
add dependency async package. it doesn't work without this package.
error msg 
>Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.ratelimit (/node_modules/ah-ratelimit-plugin/initializers/ratelimit.js:8:25)